--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2026-05-29 02:08:49

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = on;

--
-- TOC entry 4821 (class 1262 OID 32769)
-- Name: dbsiscarros; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE dbsiscarros WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Portuguese_Brazil.1252';


ALTER DATABASE dbsiscarros OWNER TO postgres;

\connect dbsiscarros

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = on;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 32891)
-- Name: acessorio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.acessorio (
    id bigint NOT NULL,
    nome character varying(20)
);


ALTER TABLE public.acessorio OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 32890)
-- Name: acessorio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.acessorio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acessorio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 32851)
-- Name: carro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carro (
    id bigint NOT NULL,
    nome character varying(20),
    marca_id bigint
);


ALTER TABLE public.carro OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 32896)
-- Name: carro_acessorio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carro_acessorio (
    carro_id bigint NOT NULL,
    acessorios_id bigint NOT NULL
);


ALTER TABLE public.carro_acessorio OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 32850)
-- Name: carro_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 32861)
-- Name: marca; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marca (
    id bigint NOT NULL,
    nome character varying(20)
);


ALTER TABLE public.marca OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 32860)
-- Name: marca_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 32918)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    password character varying(20),
    username character varying(10)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 32917)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4812 (class 0 OID 32891)
-- Dependencies: 220
-- Data for Name: acessorio; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.acessorio (id, nome) VALUES (1, 'Air bag');
INSERT INTO public.acessorio (id, nome) VALUES (2, 'Som');
INSERT INTO public.acessorio (id, nome) VALUES (3, 'Vidro elétrico');
INSERT INTO public.acessorio (id, nome) VALUES (4, 'Alarme');
INSERT INTO public.acessorio (id, nome) VALUES (6, 'Aparelho MP3');


--
-- TOC entry 4808 (class 0 OID 32851)
-- Dependencies: 216
-- Data for Name: carro; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.carro (id, nome, marca_id) VALUES (5, 'Chevette', NULL);
INSERT INTO public.carro (id, nome, marca_id) VALUES (7, 'Troller', NULL);
INSERT INTO public.carro (id, nome, marca_id) VALUES (9, 'Uno', 2);
INSERT INTO public.carro (id, nome, marca_id) VALUES (12, 'Lancer', NULL);
INSERT INTO public.carro (id, nome, marca_id) VALUES (15, 'Punto', 2);
INSERT INTO public.carro (id, nome, marca_id) VALUES (14, 'FastBack', 2);
INSERT INTO public.carro (id, nome, marca_id) VALUES (16, 'Uno Mille', 2);
INSERT INTO public.carro (id, nome, marca_id) VALUES (17, 'Palio', 2);
INSERT INTO public.carro (id, nome, marca_id) VALUES (6, 'Golf', 4);
INSERT INTO public.carro (id, nome, marca_id) VALUES (18, 'Civic', 3);
INSERT INTO public.carro (id, nome, marca_id) VALUES (19, 'Passat', 4);
INSERT INTO public.carro (id, nome, marca_id) VALUES (25, 'Ecosport', 5);
INSERT INTO public.carro (id, nome, marca_id) VALUES (27, 'Fiesta', 5);
INSERT INTO public.carro (id, nome, marca_id) VALUES (28, 'Jetta', 4);
INSERT INTO public.carro (id, nome, marca_id) VALUES (32, 'HRV', 3);
INSERT INTO public.carro (id, nome, marca_id) VALUES (33, 'Cayenne', 6);


--
-- TOC entry 4813 (class 0 OID 32896)
-- Dependencies: 221
-- Data for Name: carro_acessorio; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (17, 1);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (17, 2);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (17, 3);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (14, 1);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (14, 3);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (15, 2);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (6, 4);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (19, 2);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (19, 3);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (18, 2);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (18, 4);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (18, 3);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (28, 1);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (28, 2);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (17, 1);
INSERT INTO public.carro_acessorio (carro_id, acessorios_id) VALUES (17, 1);


--
-- TOC entry 4810 (class 0 OID 32861)
-- Dependencies: 218
-- Data for Name: marca; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.marca (id, nome) VALUES (2, 'Fiat');
INSERT INTO public.marca (id, nome) VALUES (3, 'Honda');
INSERT INTO public.marca (id, nome) VALUES (4, 'Volkswagen');
INSERT INTO public.marca (id, nome) VALUES (5, 'Ford');
INSERT INTO public.marca (id, nome) VALUES (6, 'Porsche');


--
-- TOC entry 4815 (class 0 OID 32918)
-- Dependencies: 223
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.usuario (id, password, username) VALUES (1, 'admin', 'admin');
INSERT INTO public.usuario (id, password, username) VALUES (3, '27101995', 'adnogueira');
INSERT INTO public.usuario (id, password, username) VALUES (4, 'realmadrid', 'beckham');
INSERT INTO public.usuario (id, password, username) VALUES (2, '123456', 'teste');


--
-- TOC entry 4822 (class 0 OID 0)
-- Dependencies: 219
-- Name: acessorio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.acessorio_id_seq', 6, true);


--
-- TOC entry 4823 (class 0 OID 0)
-- Dependencies: 215
-- Name: carro_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carro_id_seq', 33, true);


--
-- TOC entry 4824 (class 0 OID 0)
-- Dependencies: 217
-- Name: marca_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marca_id_seq', 6, true);


--
-- TOC entry 4825 (class 0 OID 0)
-- Dependencies: 222
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_seq', 3, true);


--
-- TOC entry 4658 (class 2606 OID 32895)
-- Name: acessorio acessorio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.acessorio
    ADD CONSTRAINT acessorio_pkey PRIMARY KEY (id);


--
-- TOC entry 4654 (class 2606 OID 32855)
-- Name: carro carro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carro
    ADD CONSTRAINT carro_pkey PRIMARY KEY (id);


--
-- TOC entry 4656 (class 2606 OID 32865)
-- Name: marca marca_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT marca_pkey PRIMARY KEY (id);


--
-- TOC entry 4660 (class 2606 OID 33054)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4662 (class 2606 OID 32904)
-- Name: carro_acessorio fk4swomvinge2sfppfkhgatdhw5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carro_acessorio
    ADD CONSTRAINT fk4swomvinge2sfppfkhgatdhw5 FOREIGN KEY (carro_id) REFERENCES public.carro(id);


--
-- TOC entry 4663 (class 2606 OID 32899)
-- Name: carro_acessorio fkpkp86yclmuj0c7mrnoyihqonm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carro_acessorio
    ADD CONSTRAINT fkpkp86yclmuj0c7mrnoyihqonm FOREIGN KEY (acessorios_id) REFERENCES public.acessorio(id);


--
-- TOC entry 4661 (class 2606 OID 32866)
-- Name: carro fkrdimwbmemo9p4j5eaf6jws1ss; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carro
    ADD CONSTRAINT fkrdimwbmemo9p4j5eaf6jws1ss FOREIGN KEY (marca_id) REFERENCES public.marca(id);


-- Completed on 2026-05-29 02:08:49

--
-- PostgreSQL database dump complete
--

